name: Print Branch Name on Push

on:
  push:
    branches:
      - '*'

jobs:
  print-branch-name:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print branch name
        run: |
          echo "Branch name is: ${GITHUB_REF#refs/heads/}"

        