name: Dependent Jobs Workflow

on:
  push:
    branches:
      - '*'  # Trigger the workflow on any branch push

jobs:
  generate-name:
    name: Generate Name
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.set-name.outputs.name }}

    steps:
      - name: Set Name
        id: set-name
        run: |
          echo "Fay Alaamri"
          echo "::set-output name=name::Fay Alaamri"

  print-name:
    name: Print Name
    runs-on: ubuntu-latest
    needs: generate-name  # This job depends on 'generate-name'

    steps:
      - name: Get and Print the Name
        run: |
          echo "The name from Job 1 is: ${{ needs.generate-name.outputs.name }}"
